<a href="https://colab.research.google.com/github/ronupanchal/ML_Algorithm_code/blob/main/Numpy_Demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Numpy Demo
*Numpy is Python Library.*

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
arr = np.array([0,1,2,3,5])
print(arr)

[0 1 2 3 5]


In [ ]:
len(arr)

5

In [ ]:
def func(arr):
  for i in arr:
    print(i)   
    i=arr[i-1]+1
    print("sum:",i)


In [ ]:
func(arr)

0
sum: 6
1
sum: 1
2
sum: 2
3
sum: 3
5
sum: 6


In [ ]:
np.__version__

'1.21.6'

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr1 = np.array(44)
arr1

array(44)

In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [ ]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2.ndim

2

In [ ]:
# 3-D Array
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [ ]:
arr3.ndim

3

In [ ]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3], [4,5,6]])
d = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [ ]:
arr5 = np.array([1,2,3,4], ndmin=5)

print(arr5)
print('number of dimensions :', arr5.ndim)


[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [ ]:
arr = np.array([1,2,3,4])
print(arr[2]+arr[3])


7


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
print('2nd element on 1st row: ', arr[1,2])

2nd element on 1st row:  8


In [ ]:
arr10 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
arr10

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr10[1,1,1]

11

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[0, -3])

Last element from 2nd dim:  3


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[::-1])

[7 6 5 4 3 2 1]


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1,-4:-1])
arr.ndim

[7 8 9]


2

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0:2,3])

[4 9]


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
arr = np.array([1,2,3,4])
print(arr.dtype)

int64


In [ ]:
arr1= np.array(['apple','banana','cherry'])
arr1.dtype

dtype('<U6')

In [ ]:
arr = np.array([1,2,3,4],dtype='S')
print(arr)
print(arr.dtype)


[b'1' b'2' b'3' b'4']
|S1


In [ ]:
arr2 = np.array([1.1,2.1,3.1])
print(arr2)
print(arr2.dtype)
newarr1 = arr2.astype('S')
print(newarr1)
print(newarr1.dtype)


[1.1 2.1 3.1]
float64
[b'1.1' b'2.1' b'3.1']
|S32


In [ ]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
x[0] = 31
print(arr)
print(x)


[1 2 3 4 5]
[31  2  3  4  5]


In [ ]:
arr = np.array([[1,2,3], [4,5,6]])
for x in arr:
  print(x)
  for i in x:
    print(i)


[1 2 3]
1
2
3
[4 5 6]
4
5
6


In [ ]:
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in np.nditer(arr):
  print(x)


1
2
3
4
5
6
7
8


In [ ]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[:,::2]):
  print(x)

1
3
5
7


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
